import{a as x,S as $,i as s}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&l(h)}).observe(document,{childList:!0,subtree:!0});function e(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(o){if(o.ep)return;o.ep=!0;const r=e(o);fetch(o.href,r)}})();async function y(n,t=1){return await x.get("https://pixabay.com/api/?key=52802727-e127d4f3f7eb26b70bb46f136&q="+n+"&orientation=horizontal&image_type=photo&safesearch=true&per_page=15&page="+t).then(e=>e.data)}const g=document.querySelector(".load_more"),b=document.querySelector(".gallery"),u=document.querySelector(".loader");let a;function L(n){const t=n.map(e=>`
      <li class="cart">
        <a class="photo_link" href="${e.largeImageURL}">
          <img class="photo_image" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="photo_info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>`).join("");b.insertAdjacentHTML("beforeend",t),a?a.refresh():a=new $(".gallery a",{captionsData:"alt",captionDelay:250}),a.on("show.simplelightbox",()=>{document.body.style.overflow="hidden"}),a.on("close.simplelightbox",()=>{document.body.style.overflow=""})}function B(){b.innerHTML=""}function w(){u&&u.classList.remove("hidden")}function i(){u&&u.classList.add("hidden")}function E(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const v=document.querySelector(".form"),p=v.elements["search-text"],S=document.querySelector(".load_more"),q={title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",timeout:3e3},m={title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"center",timeout:4e3},M={title:"Error",message:"Something went wrong. Please try again later.",position:"center",timeout:3e3};let c=1,f=0,P="";v.addEventListener("submit",_);S.addEventListener("click",()=>{O()});function _(n){n.preventDefault(),S.classList.contains("hidden")||d(),w();const t=p.value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search query.",position:"center",timeout:3e3});return}P=t,B(),y(t).then(e=>{if(e.hits.length===0){i(),s.error(q);return}L(e.hits),f=Math.ceil(e.totalHits/15),p.value="",i(),f>c?E():(d(),s.info(m))}).catch(e=>{i(),s.error(M)})}function O(){if(c<f){w();const n=P;c+=1,y(n,c).then(t=>{if(t.hits.length===0){i(),s.error(q);return}L(t.hits),i();const e=document.querySelector(".gallery .cart");if(e){const l=e.getBoundingClientRect().height;window.scrollBy({top:l*2,behavior:"smooth"})}c>=f&&(d(),s.info(m))}).catch(t=>{i(),s.error(M)})}else d(),s.info(m)}
//# sourceMappingURL=index.js.map
