import{a as P,S as $,i as s}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();async function p(n,t=1){return await P.get("https://pixabay.com/api/?key=52802727-e127d4f3f7eb26b70bb46f136&q="+n+"&orientation=horizontal&image_type=photo&safesearch=true&per_page=15&page="+t).then(e=>e.data)}const g=document.querySelector(".load_more"),y=document.querySelector(".gallery"),l=document.querySelector(".loader");function b(n){const t=n.map(e=>`
			<li class="cart">
				<a class="photo_link" href="${e.largeImageURL}">
					<img class="photo_image" src="${e.webformatURL}" alt="${e.tags}" />
				</a>
				<div class="photo_info">
					<p><b>Likes:</b> ${e.likes}</p>
					<p><b>Views:</b> ${e.views}</p>
					<p><b>Comments:</b> ${e.comments}</p>
					<p><b>Downloads:</b> ${e.downloads}</p>
				</div>
			</li>`).join("");y.insertAdjacentHTML("beforeend",t),B.refresh()}const B=new $(".gallery a",{captionsData:"alt",captionDelay:250});function E(){y.innerHTML=""}function L(){l&&l.classList.remove("hidden")}function i(){l&&l.classList.add("hidden")}function _(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const w=document.querySelector(".form"),m=w.elements["search-text"],v=document.querySelector(".load_more"),S={title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",timeout:3e3},h={title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"center",timeout:4e3},q={title:"Error",message:"Something went wrong. Please try again later.",position:"center",timeout:3e3};let a=1,d=0,M="";w.addEventListener("submit",x);v.addEventListener("click",()=>{O()});function x(n){n.preventDefault(),v.classList.contains("hidden")||u(),L();const t=m.value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search query.",position:"center",timeout:3e3});return}M=t,E(),p(t).then(e=>{if(e.hits.length===0){i(),s.error(S);return}b(e.hits),d=Math.ceil(e.totalHits/15),m.value="",i(),d>a?_():(u(),s.info(h))}).catch(e=>{i(),s.error(q)})}function O(){if(a<d){L();const n=M;a+=1,p(n,a).then(t=>{if(t.hits.length===0){i(),s.error(S);return}b(t.hits),i();const e=document.querySelector(".gallery .cart");if(e){const c=e.getBoundingClientRect().height;window.scrollBy({top:c*2,behavior:"smooth"})}a>=d&&(u(),s.info(h))}).catch(t=>{i(),s.error(q)})}else u(),s.info(h)}
//# sourceMappingURL=index.js.map
