import{a as x,S as $,i as s}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function e(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=e(o);fetch(o.href,r)}})();async function y(n,t=1){return await x.get("https://pixabay.com/api/?key=52802727-e127d4f3f7eb26b70bb46f136&q="+n+"&orientation=horizontal&image_type=photo&safesearch=true&per_page=15&page="+t).then(e=>e.data)}const g=document.querySelector(".load_more"),b=document.querySelector(".gallery"),l=document.querySelector(".loader");function L(n){const t=n.map(e=>`
			<li class="cart">
			<a class="photo_link" href="${e.largeImageURL}">
				<img class="photo_image" src="${e.webformatURL}" alt="${e.tags}" />
			</a>
			<div class="photo_info">
				<p><b>Likes:</b> ${e.likes}</p>
				<p><b>Views:</b> ${e.views}</p>
				<p><b>Comments:</b> ${e.comments}</p>
				<p><b>Downloads:</b> ${e.downloads}</p>
			</div>
		</li>`).join("");b.insertAdjacentHTML("beforeend",t),m.refresh()}const m=new $(".gallery a",{captionsData:"alt",captionDelay:250});m.on("show.simplelightbox",()=>{document.body.style.overflow="hidden",console.log("123456")});m.on("close.simplelightbox",()=>{document.body.style.overflow=""});function B(){b.innerHTML=""}function w(){l&&l.classList.remove("hidden")}function i(){l&&l.classList.add("hidden")}function E(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const v=document.querySelector(".form"),p=v.elements["search-text"],S=document.querySelector(".load_more"),q={title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",timeout:3e3},h={title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"center",timeout:4e3},M={title:"Error",message:"Something went wrong. Please try again later.",position:"center",timeout:3e3};let a=1,d=0,P="";v.addEventListener("submit",_);S.addEventListener("click",()=>{O()});function _(n){n.preventDefault(),S.classList.contains("hidden")||u(),w();const t=p.value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search query.",position:"center",timeout:3e3});return}P=t,B(),y(t).then(e=>{if(e.hits.length===0){i(),s.error(q);return}L(e.hits),d=Math.ceil(e.totalHits/15),p.value="",i(),d>a?E():(u(),s.info(h))}).catch(e=>{i(),s.error(M)})}function O(){if(a<d){w();const n=P;a+=1,y(n,a).then(t=>{if(t.hits.length===0){i(),s.error(q);return}L(t.hits),i();const e=document.querySelector(".gallery .cart");if(e){const c=e.getBoundingClientRect().height;window.scrollBy({top:c*2,behavior:"smooth"})}a>=d&&(u(),s.info(h))}).catch(t=>{i(),s.error(M)})}else u(),s.info(h)}
//# sourceMappingURL=index.js.map
